### ISSUE TITLE
Data to share

### ISSUE THREAD

**Issue by chiragnagpal** [bionlplab/heart_failure_mortality#2]
Hello 

I am a PhD student at Carnegie Mellon's Language Technologies Institute, actively involved in research in Time-to-Event prediction models with censored data.

Here is an example of research I am involved in:

https://arxiv.org/pdf/2003.01176.pdf
https://arxiv.org/abs/2101.06536

 I am looking to reproduce your experiments and wanted to see if it would be possible for you to share an anonymized data that we could use to rerun your experiments. 

I shall be very grateful 

Looking forward

Chirag

**Comment by hgjlee** [comment]
Hi Chirag, 

Thank you for reaching out! Your research certainly seems aligned with ours. I'm checking with my former advisor. I'll reach out via email once confirmed. 

Best,
Jacob

**Comment by yfpeng** [comment]
Thanks for reaching out. IRB review is required before we share the data. I will keep you posted once I have any updates.
